awful.spawn: Check arguments in once and single_instance
Doing awful.spawn.once("gvim") and awful.spawn.single_instance("gvim")
resulted in the following non-intuitive error:

2019-03-02 11:55:46 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in function 'pairs'
	lib/gears/table.lua:51: in function 'gears.table.crush'
	lib/awful/rules.lua:462: in field 'callback'
	lib/awful/rules.lua:491: in function 'awful.rules.apply'
error: lib/gears/table.lua:51: bad argument #1 to 'pairs' (table expected, got nil)

What is going on here is that thanks to startup-notification, the new
instance of GVim is found. Then, rules are applied. However, no rules
were provided.

Since this error happens only some time later, the traceback does not
say anything useful and I was at first confused at was going on.

Improve this by making sure these two functions actually get the
required arguments.

Signed-off-by: Uli Schlachter <psychon@znc.in>